---
- hosts: all
  user: vagrant
  become: true
  gather_facts: True

  tasks:
  - name: install required packages
    dnf:
      name: ntp,git,golang,libvirt-devel
      state: latest

  - name: create gopath directory
    file:
      path: $HOME/gopath
      state: directory
      mode: 0755
    become_user: vagrant

  - name: export GOPATH
    shell: "export GOPATH=$HOME/gopath"
    become_user: vagrant
