- hosts: all
  user: vagrant
  become: true
  gather_facts: false

  tasks:
  - name: install python and deps for ansible modules
    raw: dnf install -y python2 python2-dnf python-firewall libselinux-python
