---
- hosts: all
  user: vagrant
  become: true
  gather_facts: True

  tasks:
  - name: install required packages
    dnf:
      name: "{{ item }}"
      state: latest
    with_items:
      - ntp
      - tree
      - git
      - golang
      - libvirt-devel
      - mercurial
      - golang-googlecode-tools-stringer

  - name: export GOPATH
    lineinfile:
      dest: $HOME/.bashrc
      insertafter:
      line: 'export GOPATH=$HOME/gopath'
    become_user: vagrant
